more debugging of the build

diff --git a/.github/workflows/azure-static-web-apps-gentle-meadow-060b9571e.yml b/.github/workflows/azure-static-web-apps-gentle-meadow-060b9571e.yml
--- a/.github/workflows/azure-static-web-apps-gentle-meadow-060b9571e.yml
+++ b/.github/workflows/azure-static-web-apps-gentle-meadow-060b9571e.yml
@@ -28,8 +28,16 @@ jobs:
           node-version: '22.x'
       - name: Install dependencies
         run: npm ci
-      - name: Build Angular SSR app
+      - name: Build Angular app
         run: npm run build
+      - name: Check for index.html
+        run: |
+          if [ -f dist/coffee-machine-web/browser/index.html ]; then
+            echo "index.html found!"
+          else
+            echo "index.html NOT found!"
+            exit 1
+          fi
       - name: Install OIDC Client from Core Package
         run: npm install @actions/core@1.6.0 @actions/http-client
       - name: Get Id Token
